# Generated by Django 3.2.23 on 2025-05-21 07:59

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя должно содержать только буквы, цифры и символы @/./+/-/_', regex='^[\\w.@+-]+$'), users.validators.validate_username_me], verbose_name='Имя пользователя'),
        ),
    ]
